# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d69eab965a1e562bb41c477969bafba60163094fc9e0a04ed63c4d9d3fe01bba1f9acb4c80fae52803492e1c77f375494e25f37b9f3918745e98e6834e6aff5b

test:
  secret_key_base: 17483d2c69d611b261d478ea2d675bab6341764da4b93b0832459da82acd702104480c7cccfdc2d1332a35d181ef12144b11a42579a7395bb26ddc6b10b54c5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
